add readme
Kipsu/telegraph pull request #2
Opened 2022-12-15 15:58 UTC by Dsorthep

2022-12-15 16:25 UTC, mlafonta commented
If you name your PR starting with "KIPSU-25907 - {name}" it will automatically link to Jira the same as bitbucket

2022-12-15 16:29 UTC, mlafonta submitted a review, later dismissed

2022-12-15 22:45 UTC, kronning6 requested changes
Please update the title to have the ticket number

2022-12-15 22:45 UTC, kronning6 commented on README.md
> +**telegraph** is an integration platform for messaging providers. This monorepo is written in Kotlin with a Micronaut framework and Apache Camel to handle queueing.
Lets scrap `integration` from this description and change the last sentence to "This monorepo is written in Kotlin with the Micronaut framework and Apache Camel."

2022-12-15 22:45 UTC, kronning6 commented on README.md
> +To get started clone this repo. Downloading Intellij IDEA (IDE) is recommended for this Kotlin based application.
Lets capitalize the J in `IntelliJ`

2022-12-15 22:45 UTC, kronning6 commented on README.md
> +For more information on **telegraph**: [Telegraph (MPP)](https://kipsudev.atlassian.net/wiki/spaces/EN/pages/2969698317/Telegraph+MPP)
Lets spell out Message Provider Platform

2022-12-15 22:45 UTC, kronning6 commented on README.md
> +`./gradlew run` - Starts the application on port 8080.
This will change with Matt's Docker PR but lets change this to `./gradlew run --continuous`

2022-12-16 14:08 UTC, Dsorthep commented
This is a PR to add a README to this project. This README has a description of the repo along with a link to the Services doc, setup instructions with a link to download IntelliJ IDEA, and commands to start and test the application.

2022-12-16 15:20 UTC, mlafonta approved these changes
lgtm

2022-12-16 17:18 UTC, kronning6 approved these changes

2022-12-16 19:06 UTC, matthewbouc approved these changes

2022-12-16 19:20 UTC, merged