KIPSU-25910 - Add Circleci Config with a Build and a Test Workflow
Kipsu/telegraph pull request #3
Opened 2022-12-15 19:51 UTC by mlafonta

@kronning6 I also will need you to connect it in circleci here: https://app.circleci.com/settings/project/github/Kipsu/telegraph?utm_campaign=locked_project&utm_content=project_dashboard_tooltip&utm_medium=copy_admin_project_set_up_link&utm_source=circleci_onboarding

2022-12-15 21:49 UTC, matthewbouc submitted a review, later dismissed

2022-12-15 22:39 UTC, kronning6 requested changes

2022-12-15 22:39 UTC, kronning6 commented on .circleci/config.yml
> +              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
Can you add a newline at the end of the file?

2022-12-16 17:17 UTC, kronning6 approved these changes

2022-12-16 19:07 UTC, matthewbouc approved these changes

2022-12-16 19:22 UTC, merged